language: python
python: '3.7'
env:
  global:
    - SCRIPTS=https://raw.githubusercontent.com/UniversalConceptualCognitiveAnnotation/docs/master/scripts
deploy:
  provider: pypi
  user: __token__
  password:
    secure: "d361OMq//ztUH73xzjkaB+9m3rgbBTnqQZOm6midGffTZwlFe6hM3B41gpM3xR1wdGuviEQj7QjCSq6sPum9EWDwviLzG7pCPHLB+ByZDUuJe3mbbol+CJfu3dT5LRu657iievhCLwZK0KhBdUIi3EH5wJh7nuVg6RbHMTpmBvsdMSMEoO/8TbZkYt2IKZ4uey7UNhGE/+ZOOJ4RGmxJHVSEAljYv3Kh9b9Gd/wxqWXye4rDcVdz/LJ2ktSaFTvCu0EQvs07+Y9qA8ff0BF9ocQffg+Q9slZ/sU4JjKTV2Wyn1EnlZAzB55mOQpETWaxcGyYTCwNGFJKuMYL8npaJ1YojY6Yb/k9yMB5pp1Qeuzw/p6TWE7An0h4xZhNDJkKlJktyjzUAaLbZZR8d0XQwvoX+pir995YkuD2XXsL8r2ITAdntmkyb9ygtCTRQ0uWBuldVdDFcTdzwQOxBnCo5VkvFEnmEZY88kfVazgIgBH+rsnCyH2O7D+08Dr1vBtPa/9cTA5SCc6XFLJrEORt24A2OXxEeRiqbYooiQCRIyovsJMGvOqrYG0WONxS734m2/47IQcXuInq0ef2BU3qqFVTmAS5DWIhMTypvdmFQHiwiYzUIMDAEc+CSemfIEiceTKUqdam8rPLS5yPn0ndNqy/3iW+IByHMIN2mIKih1A="
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
jobs:
  include:
    - install: pip install tox-travis
      script: tox
    - install:
        - pip install -U ucca[visualize]==1.1.7 semstr[amr]==1.1.10 scikit-learn==0.20.2 tqdm depedit==2.1.4 scour
        - python -m spacy download en_core_web_md
      script:
        - URL=`git remote get-url origin`
        - python conllulex2ucca.py train/streusle.ud_train.conllulex dev/streusle.ud_dev.conllulex test/streusle.ud_test.conllulex -emo xml -v
        - git checkout --orphan xml
        - git reset -q
        - git pull origin xml || true
        - rm -f *.*
        - mv -f xml/* ./
        - rmdir xml
        - git add *.xml
        - curl $SCRIPTS/push.sh | bash || true
        - python -m scripts.visualize --format svg --node-ids *.xml -o images
        - |
          for f in images/*.svg; do
            scour -i $f -o $f.images --enable-viewboxing --enable-id-stripping --enable-comment-stripping --shorten-ids --indent=none
            mv $f.images $f -f
          done
        - git checkout --orphan images
        - git reset -q
        - git pull origin images || true
        - rm -f *.*
        - mv -f images/* ./
        - rmdir images
        - git add *.svg
        - git remote set-url origin $URL > /dev/null 2>&1
        - curl $SCRIPTS/push.sh | bash || true

