language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: __token__
  password:
    secure: "KZG6RCWM3GuqtwYUmdbKR4iNgtQ/ht2pxTYOh5lb1TO403KMcCMwdR5wTM1WcA3XKKv9xZfyLlk1Qce8wRd27t4LgxgoCmXx4Y6lCk3peXenAH60+2VgMB+m5Nlv7MOAjkQwgQ1MBr7E7UZkHPr1vNIh5EDGF0tlhONQLDSQ30J9Mg9+9lvoP9HTpOUCjmaFlKNJXRrmx//qai4mHs9L7H6LZbibgYysvPL4oOJ5AmTTpXS1UMi5hmPbBRSINaQPNfKznSmmQHCgK3oyK78uw7qRToPpnwuC566u5CipFj9maLxodikJyTxr5CQwhO33QqybaUrPdjWz7YhDeZgehMFad0PQDxd2qd4Dyut4cFBxI/a8968TbFTINCO270Eu/609mbUxv0MTdxUJhqC/6qaROZSpp4OB9zuqiJb3ZAYaqERoLSnysiV8Cg4Htz/MLHm4VbjBWtpEFb9ifJhIgSX0tRaVrse2lqOIm1E5UbhB3h/hNG/JHTjBFbm+AS3Ox3Fry6fTeoMIvgqkejqg4UOMitn4vBiKQukXCV6IpEXFXFS7VMA4rmt76RzviI5zPPdI/GlaK/QWTlCcB581EZlQnPpkWaA6mXvWdIqV8dDjs9com5NkUihLTT9gQmQaMp63XiZuzlRx7UGAeiNn9JSNXTqaqtfqe1rnpY5Wqo0="
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
