LEADERS = [
    'absolver', 'acolyte', 'administrator', 'aggressor', 'alcalde', 'amora', 'anagnost', 'antipope', 'apotheosis',
    'apparatchik', 'archbishop', 'archdeacon', 'archduchess', 'archduke', 'archpriest', 'aristocrat', 'armiger',
    'ayatollah', 'baas', 'bacchant', 'bacchante', 'bachelor', 'bachelor-at-arms', 'backbencher', 'banneret', 'baron',
    'baroness', 'baronet', 'bellwether', 'better', 'bey', 'bishop', 'boss', 'brahman', 'brahmin', 'burgomaster',
    'burgrave', 'caller', 'campaigner', 'candidate', 'canon', 'cantor', 'capo', 'captain', 'cardinal', 'cavalier',
    'celebrant', 'ceo', 'cfo', 'chair', 'chairman', 'chairperson', 'chairwoman', 'chaplain', 'chatelaine',
    'cheerleader', 'chevalier', 'chief', 'chieftain', 'choragus', 'churchman', 'cicerone', 'clergyman', 'cleric',
    'coach', 'collectivist', 'commander', 'commie', 'commissioner', 'communist', 'conditioner', 'confessor',
    'congressman', 'congresswoman', 'convener', 'counsellor', 'counselor', 'count', 'countess', 'crackerjack',
    'crossbencher', 'curate', 'czarina', 'czaritza', 'dauphin', 'dci', 'deacon', 'dean', 'demagog', 'demagogue',
    'demigod', 'deputy', 'diocesan', 'director', 'divine', 'domine', 'dominee', 'dominie', 'dominus', 'don',
    'doorkeeper', 'duce', 'duchess', 'duke', 'earl', 'ecclesiastic', 'employer', 'eparch', 'evangelist', 'ex-mayor',
    'exarch', 'executive', 'father', 'filibuster', 'filibusterer', 'flamen', 'foreman', 'forewoman', 'frontbencher',
    'fugleman', 'gaffer', 'galvaniser', 'galvanizer', 'ganger', 'general', 'god', 'gospeler', 'gospeller', 'governor',
    'grandee', 'guide', 'guru', 'guvnor', 'hack', 'handler', 'hazan', 'head', 'headman', 'hero', 'hierarch',
    'higher-up', 'hirer', 'honcho', 'hoodoo', 'hosteller', 'hotelier', 'hotelkeeper', 'hotelman', 'humdinger', 'ideal',
    'imam', 'imaum', 'initiator', 'insider', 'inspirer', 'instigator', 'internationalist', 'invigilator', 'jimdandy',
    'jimhickey', 'knight', 'knight-errant', 'lady-in-waiting', 'lama', 'landgrave', 'lawgiver', 'lawmaker', 'leader',
    'lector', 'left-winger', 'leftist', 'legislator', 'magus', 'maharaja', 'maharajah', 'maharanee', 'maharani',
    'malik', 'manager', 'manageress', 'marchioness', 'margrave', 'marquess', 'marquis', 'marquise', 'master',
    'materfamilias', 'matriarch', 'mayor', 'mayoress', 'metropolitan', 'milord', 'minister', 'ministrant', 'misleader',
    'mistress', 'model', 'moderator', 'monitor', 'nabob', 'nawab', 'noble', 'nobleman', 'noblewoman', 'nominee',
    'noncandidate', 'nonesuch', 'nonpareil', 'nonsuch', 'officiant', 'ordainer', 'ordinand', 'ordinary', 'ostiarius',
    'ostiary', 'overseer', 'oyabun', 'padre', 'padrone', 'palatine', 'palsgrave', 'paragon', 'pardoner', 'parson',
    'pastor', 'paterfamilias', 'patriarch', 'patrician', 'peer', 'peeress', 'pendragon', 'pink', 'pinko', 'pluralist',
    'pol', 'politician', 'politico', 'pontifex', 'pontiff', 'pope', 'postmaster', 'postmistress', 'postulator',
    'preacher', 'prebendary', 'prefect', 'prelate', 'president', 'prexy', 'priest', 'priest-doctor', 'priestess',
    'primate', 'primus', 'prince', 'princeling', 'princess', 'proconsul', 'proctor', 'promulgator', 'provost', 'queen',
    'rabbi', 'rabble-rouser', 'rainmaker', 'raja', 'rajah', 'ramrod', 'ranee', 'rani', 'reader', 'rector', 'registrar',
    'rep', 'representative', 'reverend', 'revisionist', 'revivalist', 'sachem', 'sagamore', 'saint', 'satrap',
    'scoutmaster', 'secretary', 'senator', 'sermoniser', 'sermonizer', 'shaman', 'shepherd', 'sire', 'socialist',
    'solon', 'spearhead', 'spoiler', 'spymaster', 'stager', 'stalking-horse', 'standard-bearer', 'statesman',
    'stateswoman', 'stationmaster', 'subdeacon', 'suffragan', 'superintendent', 'superior', 'superman', 'superordinate',
    'supervisor', 'tamer', 'taskmaster', 'taskmistress', 'taste-maker', 'technocrat', 'televangelist', 'thane',
    'thurifer', 'torchbearer', 'trainer', 'trend-setter', 'triumvir', 'tsarina', 'tsaritsa', 'tzarina',
    'undersecretary', 'vicar', 'vicereine', 'viceroy', 'viscount', 'viscountess', 'votary', 'ward-heeler', 'warlord',
    'whip', 'write-in'
]

PROFESSIONALS = [
    'abortionist', 'academic', 'academician', 'accoucheur', 'accoucheuse', 'advocate', 'aetiologist', 'alienist',
    'allergist', 'amputator', 'anaesthetist', 'analyst', 'anesthesiologist', 'anesthetist', 'angiologist', 'apothecary',
    'attorney', 'barrister', 'bibliothec', 'bonesetter', 'cardiologist', 'careerist', 'caregiver', 'cataloger',
    'cataloguer', 'catechist', 'chancellor', 'chemist', 'chiropodist', 'clinician', 'coach', 'conveyancer', 'counsel',
    'counsellor', 'counselor', 'counselor-at-law', 'craftsman', 'crammer', 'critic', 'da', 'dancing-master',
    'demonstrator', 'dentist', 'dermatologist', 'diagnostician', 'diplomate', 'doc', 'docent', 'doctor', 'don',
    'druggist', 'educator', 'electrologist', 'embryologist', 'endocrinologist', 'endodontist', 'etiologist',
    'exodontist', 'extern', 'foster-nurse', 'games-master', 'games-mistress', 'gastroenterologist', 'geriatrician',
    'gerontologist', 'governess', 'gp', 'gynaecologist', 'gynecologist', 'haematologist', 'hakeem', 'hakim', 'head',
    'head-shrinker', 'headmaster', 'headmistress', 'hematologist', 'homeopath', 'homoeopath', 'houseman', 'housemaster',
    'hygienist', 'inoculator', 'instructor', 'instructress', 'intern', 'interne', 'internist', 'lawyer', 'lector',
    'lecturer', 'librarian', 'lpn', 'master', 'matron', 'md', 'medic', 'medico', 'midwife', 'missionary', 'mistress',
    'neurologist', 'neurosurgeon', 'np', 'nurse', 'nurse-midwife', 'obstetrician', 'oculist', 'oncologist',
    'ophthalmologist', 'orthodontist', 'orthopaedist', 'orthopedist', 'orthoptist', 'otolaryngologist', 'otologist',
    'otorhinolaryngologist', 'paediatrician', 'pathologist', 'pcp', 'pedagog', 'pedagogue', 'pediatrician',
    'pediatrist', 'pedodontist', 'perinatologist', 'periodontist', 'pharmacist', 'pharmacologist', 'physician',
    'pleader', 'podiatrist', 'practician', 'practitioner', 'preceptor', 'principal', 'probationer', 'proctologist',
    'prof', 'professional', 'professor', 'prosecutor', 'prosthodontist', 'psychiatrist', 'psychoanalyst', 'publisher',
    'quack', 'radiographer', 'radiologist', 'radiotherapist', 'reader', 'referee', 'resident', 'rheumatologist',
    'rhinolaryngologist', 'rn', 'sawbones', "schoolma'am", 'schoolmarm', 'schoolmaster', 'schoolmistress',
    'schoolteacher', 'sergeant', 'sergeant-at-law', 'serjeant', 'serjeant-at-law', 'shrink', 'solicitor', 'specialist',
    'surgeon', 'teacher', 'tutor', 'urologist', 'vaccinator', 'vet', 'veterinarian', 'veterinary', 'yuppie'
]

WORKERS = [
    'abbreviator', 'abridger', 'accomplice', 'accumulator', 'adjutant', 'admiral', 'aeronaut', 'aesthetician', 'agent',
    'aide', 'aide-de-camp', 'aircraftman', 'aircraftsman', 'aircrewman', 'airman', 'airwoman', 'alcalde', 'almoner',
    'amah', 'amanuensis', 'ambassador', 'ambassadress', 'angler', 'animator', 'anthologist', 'apparatchik', 'appointee',
    'aquanaut', 'armiger', 'armor-bearer', 'armorer', 'armourer', 'arouser', 'arrowsmith', 'artificer', 'artilleryman',
    'artisan', 'assessor', 'assistant', 'associate', 'astrogator', 'attendant', 'attender', 'auto-mechanic',
    'auxiliary', 'aviator', 'aviatress', 'aviatrix', 'ayah', 'baggageman', 'bagger', 'bagman', 'bailiff', 'baker',
    'balloonist', 'barber', 'bargee', 'bargeman', 'barkeep', 'barkeeper', 'barmaid', 'barman', 'barnstormer',
    'bartender', 'baster', 'batman', 'beadle', 'beater', 'beautician', 'bellboy', 'bellhop', 'bellman', 'blackleg',
    'blacksmith', 'blaster', 'bleacher', 'bluejacket', "bo's'n", "bo'sun", 'boater', 'boatman', 'boatswain',
    'bombardier', 'bookbinder', "bos'n", 'bosun', 'bowdleriser', 'bowdlerizer', 'boxer', 'bracero', 'brakeman',
    'breadwinner', 'breaker', 'bricklayer', 'bridesmaid', 'brigadier', 'buckaroo', 'buckeroo', 'bunny', 'bureaucrat',
    'busboy', 'bushwhacker', 'butcher', 'butler', 'cabinetmaker', 'caddie', 'calligrapher', 'calligraphist',
    'cannoneer', 'canoeist', 'canvasser', 'captain', 'car-mechanic', 'carabineer', 'carabinier', 'carbineer',
    'caretaker', 'carhop', 'carpenter', 'carrier', 'carter', 'cartwright', 'carver', 'caseworker', 'caster',
    "cat's-paw", 'cattleman', 'cavalryman', 'censor', 'ceramicist', 'ceramist', 'chambermaid', 'char', 'chargeman',
    'charioteer', 'charwoman', 'checker', 'chef', 'chimneysweep', 'chimneysweeper', 'churchwarden', 'cleaner', 'clerk',
    'clockmaker', 'clocksmith', 'co-pilot', 'coachbuilder', 'coachman', 'coadjutor', 'coalman', 'coastguardsman', 'cog',
    'coiffeur', 'coiffeuse', 'coiner', 'collector', 'collier', 'colonel', 'comber', 'commandant', 'commander',
    'commando', 'commissar', 'commodore', 'companion', 'compositor', 'conductor', 'conductress', 'confederate',
    'conscript', 'consul', 'cook', 'cookie', 'cooky', 'cooper', 'copilot', 'coppersmith', 'copyist', 'copyreader',
    'copywriter', 'cornhusker', 'corporal', 'cosmetician', 'counterman', 'counterperson', 'counterwoman', 'courser',
    'courtier', 'cowboy', 'cowgirl', 'cowhand', 'cowherd', 'cowman', 'cowpoke', 'cowpuncher', 'cox', 'coxswain',
    'coyote', 'craftsman', 'crewman', 'cropper', 'cuirassier', 'cupbearer', 'currier', 'cutter', 'da', 'dairymaid',
    'dairyman', 'darner', 'deacon', 'deaconess', 'deckhand', 'decoy', 'deliverer', 'deliveryman', 'demonstrator',
    'denturist', 'deputy', 'die-sinker', 'diemaker', 'diesinker', 'digger', 'diplomat', 'diplomatist', 'dishwasher',
    'dispatcher', 'dock-walloper', 'docker', 'dockhand', 'dockworker', 'doge', 'dogfighter', 'domestic', 'doorkeeper',
    'doughboy', 'doula', 'draftee', 'draftsman', 'draftsperson', 'dragger', 'dragoon', 'draughtsman', 'dresser',
    'driver', 'drover', 'drudge', 'dyer', 'earner', 'editor', 'elder', 'electrician', 'electroplater', 'embalmer',
    'embassador', 'employable', 'employee', 'enforcer', 'engraver', 'ensign', 'enumerator', 'envoy', 'equerry',
    'escort', 'esquire', 'esthetician', 'ex-serviceman', 'excavator', 'exciseman', 'expurgator', 'facilitator',
    'factotum', 'falconer', 'faller', 'familiar', 'famulus', 'farmerette', 'farmhand', 'farrier', 'fellah', 'feller',
    'ferryman', 'fieldhand', 'filer', 'finisher', 'fireman', 'fisher', 'fisherman', 'fixer', 'flanker', 'flier',
    'floater', 'floorwalker', 'flunkey', 'flunky', 'flyer', 'fo', 'fodder', 'footman', 'footslogger', 'forger',
    'forty-niner', 'founder', 'fowler', 'framer', 'free-lance', 'freelance', 'freelancer', 'fuller', 'fumigator',
    'functionary', 'fusilier', 'gaffer', 'gallant', 'galvaniser', 'galvanizer', 'gardener', 'garnishee', 'gasman',
    'gatherer', 'gaucho', 'general', 'generalissimo', 'gentleman', 'gilder', 'gillie', 'gipsy', 'glass-cutter',
    'glassblower', 'glassworker', 'glazer', 'glazier', 'gleaner', 'goatherd', 'gob', 'gofer', 'gold-beater',
    'goldbeater', 'goldbrick', 'gondolier', 'gondoliere', 'gravedigger', 'grenadier', 'greyback', 'grip', 'groom',
    'groomsman', 'groundkeeper', 'groundskeeper', 'groundsman', 'guardsman', 'guestworker', 'guide', 'gunner',
    'gunsmith', 'gutter', 'gypsy', 'hairdresser', 'hairstylist', 'hand', 'handmaid', 'handmaiden', 'handyman', 'hanger',
    'hangover', 'harpooneer', 'harpooner', 'harvester', 'hawker', 'headwaiter', 'heaver', 'hedger', 'helmsman', 'help',
    'helper', 'herder', 'herdsman', 'hewer', 'hire', 'hireling', 'hodman', 'holdover', 'horseshoer', 'hostess',
    'hostler', 'housebreaker', 'housekeeper', 'housemaid', 'housewrecker', 'hunter', 'huntress', 'huntsman', 'hussar',
    'iceman', 'incumbent', 'independent', 'indexer', 'inductee', 'infantryman', 'instrument', 'internuncio',
    'invalidator', 'itinerant', 'jack', 'jack-tar', 'jawan', 'jobholder', 'joiner', 'journeyman', 'judge', 'jurist',
    'justice', 'justiciar', 'justiciary', 'kamikaze', 'knacker', 'kp', 'laborer', 'labourer', 'lacer', 'lackey',
    'laminator', 'lamplighter', 'lancer', 'lapidary', 'lapidist', 'lascar', 'lasher', 'lather', 'laundress',
    'laundryman', 'laundrywoman', 'leatherneck', 'ledgeman', 'legionary', 'legionnaire', 'letterer', 'licenser',
    'lieutenant', 'lifeguard', 'lifesaver', 'lighterman', 'lineman', 'linesman', 'linkboy', 'linkman', 'lion-hunter',
    'lister', 'litter-bearer', 'liveryman', 'loader', 'lobsterback', 'lobsterman', 'lockkeeper', 'lockman',
    'lockmaster', 'locksmith', 'logger', 'longshoreman', 'lovely', 'lumberjack', 'lumberman', 'lumper', 'luthier',
    'mace', 'macebearer', 'macer', 'machinist', 'magistrate', 'mahout', 'maid', 'maidservant', 'mailman', 'major',
    'major-domo', 'major-general', 'man-at-arms', 'manakin', 'mandarin', 'manicurist', 'manikin', 'mannequin',
    'mannikin', 'manservant', 'mapper', 'marcher', 'marine', 'mariner', 'marshal', 'marshall', 'mason', 'master',
    'master-at-arms', 'mate', 'mechanic', 'melter', 'mender', 'menial', 'metalworker', 'midinette', 'militiaman',
    'milkmaid', 'milkman', 'mill-girl', 'mill-hand', 'miller', 'millwright', 'minder', 'miner', 'mineworker',
    'minister', 'minter', 'mixologist', 'model', 'moneyer', 'monitrice', 'moonlighter', 'mopper', 'mortician',
    'mounter', 'mover', 'muleteer', 'musketeer', 'muzzler', 'nailer', 'navigator', 'navvy', 'newsboy', 'noncom',
    'noncombatant', 'notary', 'noticer', 'nullifier', 'nuncio', 'oarsman', 'oarswoman', 'occupier', 'oceanaut',
    'office-bearer', 'officeholder', 'officer', 'official', 'oiler', 'oilman', 'optician', 'orderly', 'ordinary',
    'ostler', 'packer', 'paddler', 'page', 'painter', 'pantryman', 'paper-pusher', 'paperboy', 'paperer', 'paperhanger',
    'para', 'paralegal', 'paramedic', 'paramedical', 'paraprofessional', 'paratrooper', 'parer', 'parlormaid',
    'parlourmaid', 'part-timer', 'paster', 'pawn', 'peacekeeper', 'peasant', 'peeler', 'penpusher', 'pensionary',
    'peon', 'perfecter', 'phlebotomist', 'picker', 'pigman', 'pilot', 'pin-up', 'pistoleer', 'pitchman', 'pitman',
    'placeman', 'placeseeker', 'plaiter', 'planter', 'plasterer', 'platelayer', 'plater', 'plenipotentiary', 'plier',
    'plotter', 'ploughman', 'ploughwright', 'plower', 'plowman', 'plowwright', 'plumber', 'plyer', 'po', 'poilu',
    'porter', 'poser', 'poster', 'postman', 'potboy', 'pothunter', 'potman', 'potter', 'praetor', 'presbyter',
    'preserver', 'pressman', 'pretor', 'printer', 'private', 'privateer', 'privateersman', 'processor', 'proconsul',
    'procurator', 'projectionist', 'prompter', 'proofreader', 'propman', 'prosecutor', 'prospector', 'provincial',
    'pruner', 'publican', 'puller', 'puncher', 'punter', 'purser', 'qadi', 'quaestor', 'quarrier', 'quarryman',
    'quartermaster', 'racker', 'ragsorter', 'rail-splitter', 'railroader', 'railwayman', 'ranger', 'ranker',
    'rapporteur', 'rat', 'rat-catcher', 'reader', 'reaper', 'receptionist', 'record-keeper', 'recorder', 'recruit',
    'recruiter', 'recruiting-sergeant', 'redact', 'redactor', 'redcap', 'redcoat', 'refiner', 'refinisher', 'registrar',
    'regular', 'regulator', 'remover', 'renovator', 'repairer', 'repairman', 'reservist', 'restorer', 'retainer',
    'reviser', 'rewriter', 'rifleman', 'rigger', 'riveter', 'rivetter', 'roadman', 'roaster', 'rocker', 'roofer',
    'rope-maker', 'ropemaker', 'roper', 'roundsman', 'rouser', 'roustabout', 'router', 'rower', 'saceur', 'saclant',
    'sacristan', 'sailor', 'salesclerk', 'salesgirl', 'saleslady', 'salesman', 'salesperson', 'saleswoman', 'salter',
    'sandwichman', 'sawyer', 'scab', 'sceneshifter', 'scorer', 'scourer', 'scpo', 'scratcher', 'scribe', 'scrivener',
    'scrubber', 'sculler', 'scullion', 'seafarer', 'seal', 'sealer', 'seaman', 'searcher', 'seasonal', 'seasoner',
    'second', 'second-in-command', 'secretary', 'selectman', 'selectwoman', 'seneschal', 'sergeant', 'serjeant-at-arms',
    'servant', 'server', 'serviceman', 'servitor', 'setter', 'settler', 'sexton', 'sharecropper', 'shearer',
    'sheepherder', 'sheepman', 'sheller', 'shelver', 'shepherd', 'shepherdess', 'shifter', 'shill', 'shingler',
    'shipbuilder', 'shipwright', 'shopwalker', 'shoveler', 'shoveller', 'sidesman', 'signalman', 'sitter', 'skidder',
    'skinner', 'skipper', 'skivvy', 'skycap', 'slaughterer', 'slave', 'slavey', 'smith', 'smsgt', 'snarer', 'solderer',
    'soldier', 'sommelier', 'sorter', 'soundman', 'sourdough', 'splicer', 'splitter', 'sponger', 'spot-welder',
    'spotter', 'sprayer', 'sprigger', 'sprog', 'squire', 'stableboy', 'stableman', 'stacker', 'staffer', 'stagehand',
    'stainer', 'stalker', 'stamper', 'standard-bearer', 'steamfitter', 'steeplejack', 'steerer', 'steersman', 'stemmer',
    'stenographer', 'stevedore', 'steward', 'stewardess', 'stipendiary', 'stippler', 'stitcher', 'stock-taker',
    'stocktaker', 'stoker', 'stonecutter', 'stonemason', 'strafer', 'stretcher-bearer', 'strikebreaker', 'striker',
    'stringer', 'striper', 'stripper', 'striver', 'stroke', 'stuffer', 'styler', 'stylist', 'subaltern', 'subeditor',
    'sublieutenant', 'submariner', 'subordinate', 'subsidiary', 'supercargo', 'supermodel', 'supporter', 'swagger',
    'swaggie', 'swagman', 'sweep', 'sweeper', 'swineherd', 'tacker', 'tallyman', 'tanker', 'tanner', 'tapper',
    'tapster', 'tar', 'taxer', 'taxidermist', 'taxman', 'teamster', 'teaser', 'techie', 'technician', 'tekki', 'teller',
    'temp', 'temporary', 'tender', 'territorial', 'thatcher', 'thrower', 'throwster', 'tier', 'tiler', 'timekeeper',
    'tinker', 'tinner', 'tinsmith', 'tinter', 'toiler', 'toller', 'tollgatherer', 'tollkeeper', 'tollman', 'topper',
    'touch-typist', 'tracker', 'tracklayer', 'trainbandsman', 'trainbearer', 'trainman', 'trainmaster', 'trapper',
    'trawler', 'trencher', 'trier', 'trimmer', 'troller', 'trooper', 'troubleshooter', 'trustbuster', 'tugger', 'tuner',
    'turncock', 'turner', 'turtler', 'twiner', 'typesetter', 'typist', 'typographer', 'underboss', 'underling',
    'undertaker', 'unionist', 'upholsterer', 'usher', 'usherette', 'valet', 'vaquero', 'varlet', 'varnisher', 'verger',
    'vestryman', 'vestrywoman', 'vet', 'veteran', 'vicar-general', 'vice-regent', 'vigilante', 'vintager', 'vizier',
    'voicer', 'voider', 'voluntary', 'volunteer', 'vulcaniser', 'vulcanizer', 'waggoner', 'waggonwright', 'wagoner',
    'wagonwright', 'wainwright', 'waiter', 'waitress', 'waker', 'wall-paperer', 'wallah', 'wallpaperer', 'warehouseman',
    'warehouser', 'washer', 'washerman', 'washerwoman', 'washwoman', 'waterer', 'waterman', 'weaver', 'webmaster',
    'weeder', 'weigher', 'welder', 'wetter', 'whaler', 'wheeler', 'wheelwright', 'whipper-in', 'winder', 'wingman',
    'wiper', 'wireman', 'wirer', 'woodcarver', 'woodcutter', 'woodman', 'woodsman', 'woodworker', 'worker',
    'workingman', 'workman', 'workmate', 'wrangler', 'wrecker', 'wright', 'yachtsman', 'yachtswoman', 'yardbird',
    'yardman', 'yardmaster'
]

RELNOUNS = LEADERS + PROFESSIONALS + WORKERS + ['family', 'guest', 'host', 'staff', 'team']

"""
The above lists of LEADERS, PROFESSIONALS, WORKERS were created using WordNet:

from nltk.corpus import wordnet as wn

def all_hyponyms(synset):
    hh = set(n.lower() for n in synset.lemma_names() if '_' not in n and not n.istitle())
    for hypo in synset.hyponyms():
        hh |= all_hyponyms(hypo)
    return hh

all_hyponyms(wn.synsets('leader')[0])
etc.
"""
